name: Deploy to WP Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.5
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        CACHE_CLEAR: TRUE
        TPO_PATH: "wp-content/themes/openhouse/"

      # Branches & Environments
        STG_BRANCH: staging
        STG_ENV: brisbaneopestg
